[project]
name = "dlt-nyc-taxi-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dlt[duckdb, workspace]>=1.22.0",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "requests>=2.32.5",
]
